updated Dockerfile

diff --git a/src/frontend/Dockerfile.dev b/src/frontend/Dockerfile.dev
--- a/src/frontend/Dockerfile.dev
+++ b/src/frontend/Dockerfile.dev
@@ -1,6 +1,16 @@
 FROM node:18-alpine
 
+RUN apk add --no-cache libc6-compat
+
 WORKDIR /app/src/frontend
+
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
 COPY . /app
 
@@ -10,4 +20,9 @@ RUN pnpm i
 
 EXPOSE 3000
 
-CMD ["pnpm", "dev"]
+CMD \
+    if [ -f yarn.lock ]; then yarn dev; \
+    elif [ -f package-lock.json ]; then npm run dev; \
+    elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
+    else npm run dev; \
+    fi
